services:
  db:
    image: postgres:17
    container_name: baby-vote-db
    environment:
      POSTGRES_USER: baby
      POSTGRES_PASSWORD: vote
      POSTGRES_DB: babyvote
    ports:
      - "5432:5432"
    volumes:
      - ./backend/.pgdata:/var/lib/postgresql/data
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro